# Generated by Django 4.2.30 on 2026-06-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0002_remove_producto_stock_producto_cantidad_and_more'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField()),
                ('cliente', models.ForeignKey(db_column='cliente_idcliente', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('producto', models.ForeignKey(db_column='producto_id1', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
    ]
