# Generated by Django 4.2 on 2026-06-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
