# Generated by Django 4.2.30 on 2026-06-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
